#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer proporciona un cargador de clases conveniente, generado automáticamente
| para nuestra aplicación. Sólo necesitamos utilizarlo! Lo necesitaremos
| en el guión aquí para que no tengamos que preocuparnos por la
| carga de cualquiera de nuestras clases "manualmente". Se siente muy bien para relajarse.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| Cuando ejecutemos la aplicación de la consola, el comando CLI actual será
| Ejecutado en esta consola y la respuesta enviada a un terminal.
| u otro dispositivo de salida para los desarrolladores. ¡Aquí va nada!
|
*/

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Una vez que Artisan haya terminado de correr, dispararemos los eventos de apagado.
| Para que cualquier trabajo final pueda ser realizado por la aplicación antes de cerrar
| abajo el proceso. Esto es lo último que le pasa a la solicitud.
|
*/

$kernel->terminate($input, $status);

exit($status);
